=== eclipse-opensmartclide/smartclide-context/smartclide-monitoring/src/test/resources/config/services-config.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.atb-bremen.de"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="services">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="service" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="host"/>
                                        <xs:element type="xs:anyURI" name="location"/>
                                        <xs:element type="xs:string" name="name"/>
                                        <xs:element type="xs:string" name="server"/>
                                        <xs:element type="xs:string" name="proxy"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="id" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== eclipse-opensmartclide/smartclide-context/smartclide-monitoring/src/test/resources/config/services-config.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns="http://www.atb-bremen.de"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.atb-bremen.de services-config.xsd">

    <services>
        <service id="AmIMonitoring">
            <host>localhost</host>
            <location>http://localhost:19001</location>
            <name>AmIMonitoringService</name>
            <server>org.eclipse.opensmartclide.context.services.AmIMonitoringService</server>
            <proxy>org.eclipse.opensmartclide.context.services.IAmIMonitoringService</proxy>
        </service>
        <service id="AmI-repository">
            <host>localhost</host>
            <location>http://localhost:19002</location>
            <name>AmIMonitoringDataRepositoryService</name>
            <server>org.eclipse.opensmartclide.context.services.AmIMonitoringDataRepositoryService</server>
            <proxy>org.eclipse.opensmartclide.context.services.IAmIMonitoringDataRepositoryService</proxy>
        </service>
        <service id="PersistenceUnitService">
            <host>localhost</host>
            <location>http://localhost:19004</location>
            <name>PersistenceUnitService</name>
            <server>org.eclipse.opensmartclide.context.services.PersistenceUnitService</server>
            <proxy>org.eclipse.opensmartclide.core.services.IPersistenceUnitService</proxy>
        </service>
    </services>
</config>
